name: 🚀 Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🟢 Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: 🏗️ Build Angular (producción)
        run: npm run build -- --configuration production

      - name: 📁 Preparar archivos para deploy
        run: cp -r dist/browser deploy_output

      # 🧹 Limpiar carpeta del servidor
      - name: 🧹 Limpiar servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 5m
          script: rm -rf /var/www/ds2/movify/movify-frontend/*

      # 🚀 Subir build al servidor
      - name: 🚀 Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy_output/"
          target: "/var/www/ds2/movify/movify-frontend"
          strip_components: 1

      # ✅ Verificar archivos en servidor
      - name: ✅ Verificar deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: ls -la /var/www/ds2/movify/movify-frontend/
